spring:
  application:
    name: fsmile
  datasource:
    url: jdbc:${FSMILE_DATABASE_TYPE:postgresql}://${FSMILE_DATABASE_HOST:10.1.1.36}:${FSMILE_DATABASE_PORT:5432}/${FSMILE_DATABASE_NAME:fsmile}
    username: ${FSMILE_DATABASE_USER:admin}
    password: ${FSMILE_DATABASE_PASSWORD:admin}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.${FSMILE_DATABASE_DIALECT:PostgresPlusDialect}
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/fsmile
          jwk-set-uri: http://localhost:8080/realms/fsmile/protocol/openid-connect/certs

server:
  port: 1200
springdoc:
  swagger-ui:
    path: /api/doc
