spring:
  application:
    name: fsmile
  datasource:
    url: ${FSMILE_DATABASE_URI:jdbc:postgresql://localhost:5432/fsmile}
    username: ${FSMILE_DATABASE_USER:admin}
    password: ${FSMILE_DATABASE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${FSMILE_OAUTH2_ISSUER_URI:http://localhost:8080/realms/fsmile}
          jwk-set-uri: ${FSMILE_OAUTH2_JWK_SET_URI:http://localhost:8080/realms/fsmile/protocol/openid-connect/certs}

server:
  port: 1200
springdoc:
  swagger-ui:
    path: /api/doc
